coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 0%
ignore:
  - "target/**"
  - "tests/**"
