name: Bug Report
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: Thank you for filing a bug report!
  - type: textarea
    id: problem
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicate the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      value: |
        I tried this:

        1. `gman`

        I expected this to happen:

        Instead, this happened:
  - type: textarea
    id: gman-log
    attributes:
      label: G-Man log
      description: Include the G-Man log file to help diagnose the issue.
      value: |
        | OS      | Log file location                                     |
        | ------- | ----------------------------------------------------- |
        | Linux   | `~/.cache/gman/gman.log`                      |
        | Mac     | `~/Library/Logs/gman/gman.log`                |
        | Windows | `C:\Users\<User>\AppData\Local\gman\gman.log` |

        ```
        please provide a copy of your gman log file here if possible, you may need to redact some of the lines
        ```

  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: Linux / macOS / Windows
    validations:
      required: true
  - type: input
    id: terminal-emulator
    attributes:
      label: Terminal Emulator
      placeholder: wezterm 20220101-133340-7edc5b5a
    validations:
      required: true
  - type: input
    id: gman-version
    attributes:
      label: G-Man Version
      description: >
        G-Man version (`gman --version` if using a release, `git describe` if building
        from main).
        **Make sure that you are using the [latest gman release](https://github.com/Dark-Alex-17/gman/releases) or a newer main build**
      placeholder: "gman 0.1.0"
    validations:
      required: true
